# Generated by Django 3.2.6 on 2021-08-07 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trashcan', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='occupancy',
            old_name='fk',
            new_name='can',
        ),
    ]
