# Generated by Django 3.2.6 on 2021-08-07 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trashcan', '0002_rename_fk_occupancy_can'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='occupancy',
            options={'ordering': ['time']},
        ),
    ]
